@startuml
class Solution44{
    +main()
    -scanInput() : searchName
}

class ProductSearch{
    -readJSON() : productsList
    +productSearch(searchName, productList)
}

Solution44 <|--ProductSearch
@enduml