@startuml
class Solution43{
    String siteName
    String author
    boolean jsAnswer
    boolean cssAnswer

    +main(String[])
    'html.createHTML(siteName, author)
    'html.createFolders(siteName, jsAnswer, cssAnswer)
}

class CreateStuff{
    +createHTML(siteName, author)
    +createFolders(siteName, js, css)
}

Solution43 <|-- CreateStuff

@enduml