@startuml

class Solution41{
    +Path path
    +Scanner inputFile
    +List<String> sortedNames


    +main()
    +scanInput(scanner) : namesList
    +printFile(sortedNames)
}

class SortList{
    getSortedList(namesList) : sortedNames
}

Solution41 <|-- SortList

@enduml