@startuml
class Solution42{
    +main()
    +BufferReader reader
    +List<Map<String, String>> employeeList
}

class PrintTable{
    +printTheTable(employeeList)
}

class ScanEmployeesToList{
    +ScanInFile(reader)
}

Solution42 <|-- PrintTable
Solution42 <|-- ScanEmployeesToList

@enduml